exclude: "^docs/|devcontainer.json"
default_stages: [pre-commit]

default_language_version:
    python: python3.11

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          #   - id: trailing-whitespace
          #   - id: debug-statements
          #   - id: check-builtin-literals
          - id: end-of-file-fixer
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: check-case-conflict
          - id: check-docstring-first
          - id: detect-private-key

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.1
      hooks:
          # Linter
          - id: ruff
            args:
                [
                    --no-cache,
                    --fix,
                    --exit-non-zero-on-fix,
                    --config,
                    "pyproject.toml",
                ]
          # Formatter
          - id: ruff-format
            args: [--config, "pyproject.toml"]

    # - repo: https://github.com/igorshubovych/markdownlint-cli
    #   rev: "v0.47.0"
    #   hooks:
    #       - id: markdownlint
    #         args: ["-f"]
    #         stages: [pre-commit]

    # - repo: https://github.com/facebook/pyrefly-pre-commit
    #   rev: 0.52.0 # Note: this is the version of the pre-commit hook, NOT the pyrefly version used for type checking
    #   hooks:
    #       - id: pyrefly-check
    #         name: Pyrefly (type checking)
    #         pass_filenames: false # Recommended to do full repo checks. However, you can change this to `true` to only check changed files
    #         language: system # Use system-installed pyrefly

ci:
    autoupdate_schedule: weekly
    skip: []
    submodules: false
